/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\maroonCastle2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/maroonCastle2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Acacia_Fence.geometry} material={materials.acacia_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Acacia_Slab.geometry} material={materials.acacia_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Acacia_Stairs.geometry} material={materials.acacia_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Acacia_Trapdoor.geometry} material={materials.acacia_trapdoor} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Birch_Fence.geometry} material={materials.birch_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Birch_Stairs.geometry} material={materials.birch_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Birch_Wood_Planks.geometry} material={materials.birch_planks} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Black_Stained_Glass_Pane_1.geometry} material={materials.black_stained_glass} />
        <mesh geometry={nodes.Black_Stained_Glass_Pane_2.geometry} material={materials.black_stained_glass_pane_top} />
      </group>
      <mesh geometry={nodes.Brick_Wall.geometry} material={materials.bricks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Dark_Oak_Button.geometry} material={materials.dark_oak_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Dark_Prismarine.geometry} material={materials.dark_prismarine} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Dark_Prismarine_Slab.geometry} material={materials.dark_prismarine} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Dark_Prismarine_Slab001.geometry} material={materials.dark_prismarine} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Dark_Prismarine_Stairs.geometry} material={materials.dark_prismarine} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Double_Jungle_Slab.geometry} material={materials.jungle_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Double_Mangrove_Slab.geometry} material={materials.mangrove_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Double_Warped_Slab.geometry} material={materials.warped_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Green_Terracotta.geometry} material={materials.green_terracotta} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Jungle_Slab.geometry} material={materials.jungle_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Jungle_Stairs.geometry} material={materials.jungle_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Jungle_Trapdoor.geometry} material={materials.jungle_trapdoor} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Lantern.geometry} material={materials.lantern} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Lectern_1.geometry} material={materials.oak_planks} />
        <mesh geometry={nodes.Lectern_2.geometry} material={materials.lectern_top} />
        <mesh geometry={nodes.Lectern_3.geometry} material={materials.lectern_sides} />
        <mesh geometry={nodes.Lectern_4.geometry} material={materials.lectern_base} />
        <mesh geometry={nodes.Lectern_5.geometry} material={materials.lectern_front} />
      </group>
      <mesh geometry={nodes.Mangrove_Button.geometry} material={materials.mangrove_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mangrove_Fence.geometry} material={materials.mangrove_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mangrove_Fence_Gate.geometry} material={materials.mangrove_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mangrove_Planks.geometry} material={materials.mangrove_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mangrove_Slab.geometry} material={materials.mangrove_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mangrove_Stairs.geometry} material={materials.mangrove_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mangrove_Trapdoor.geometry} material={materials.mangrove_trapdoor} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mud_Brick_Wall.geometry} material={materials.mud_bricks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Oak_Planks.geometry} material={materials.oak_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Prismarine_Brick_Slab.geometry} material={materials.prismarine_bricks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Prismarine_Brick_Stairs.geometry} material={materials.prismarine_bricks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Red_Nether_Brick_Wall.geometry} material={materials.red_nether_bricks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Red_Sandstone_Wall.geometry} material={materials.red_sandstone} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Sandstone_1.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.Sandstone_2.geometry} material={materials.sandstone_bottom} />
      </group>
      <mesh geometry={nodes.Sandstone_Wall.geometry} material={materials.sandstone} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Shroomlight.geometry} material={materials.shroomlight} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Smooth_Sandstone.geometry} material={materials.sandstone_top} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Smooth_Sandstone_Stairs.geometry} material={materials.sandstone_top} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Stone.geometry} material={materials.stone} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Stripped_Birch_Log_1.geometry} material={materials.stripped_birch_log} />
        <mesh geometry={nodes.Stripped_Birch_Log_2.geometry} material={materials.stripped_birch_log_top} />
      </group>
      <mesh geometry={nodes.Stripped_Mangrove_Wood.geometry} material={materials.stripped_mangrove_log} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Stripped_Oak_Wood.geometry} material={materials.stripped_oak_log} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Warped_Slab.geometry} material={materials.warped_planks} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Warped_Trapdoor.geometry} material={materials.warped_trapdoor} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Warped_Wart_Block.geometry} material={materials.warped_wart_block} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[130.862, 69.519, 52.832]} />
    </group>
  )
}

useGLTF.preload('/maroonCastle2.glb')
